# https://docs.microsoft.com/azure/devops/pipelines/process/approvals?view=azure-devops&WT.mc_id=DOP-MVP-5001655
trigger:
- main

pool:
  vmImage: ubuntu-latest

lockBehavior: sequential

stages:
- stage: A
  jobs:
  - deployment: Job
    environment: RunLatest
    strategy:
     runOnce:
       deploy:
         steps:
           - script: sleep 30

  - job: Job2
    dependsOn: Job
    steps:
    - script: sleep 30

