# https://docs.microsoft.com/azure/devops/pipelines/process/approvals?view=azure-devops&WT.mc_id=DOP-MVP-5001655
trigger:
- main

pool:
  vmImage: ubuntu-latest

lockBehavior: runLatest

stages:
- stage: A
  jobs:
  - job: Pre
    steps:
    - script: echo "hi!"

  - deployment: Job
    dependsOn: Pre
    environment: RunLatest
    strategy:
     runOnce:
       deploy:
         steps:
           - script: sleep 30

  - job: Job2
    dependsOn: Job
    steps:
    - script: echo "hey!"

